<!-- BEGIN HAPPY CLIENT SECTION -->
<div class="section bg-light">
    <div class="container">
        <div class="section-heading">
            <div class="inner-border"></div>
            <h3>Newsletter</h3>
        </div><!-- /.section-heading -->

        <div id="owl-testimonial" class="owl-carousel testimonial">
            <div class="item">
                <p class="text-testi">
                    <?php echo $message; ?>
                </p>
            </div><!-- /.item -->
        </div>
    </div><!-- /.container -->
</div><!-- /.section -->
<!-- END HAPPY CLIENT SECTION -->



<!-- BEGIN CLIENT LOGO SECTION -->
<div class="section">
    <div class="container">
        <?php echo $this->partial('partial/page/banners'); ?>
    </div><!-- /.container -->
</div><!-- /.section -->
<!-- END CLIENT LOGO SECTION -->