<!-- BEGIN HEADER FULL IMAGE SLIDE -->
<div class="full-slide-image" id="full-img-slide">
    <div class="slide-inner">
        <?php echo $this->partial('partial/page/slider', array('items' => $items)); ?>
    </div><!-- /.slide-inner -->
</div><!-- /.full-slide-image -->
<!-- END HEADER FULL IMAGE SLIDE -->



<!-- BEGIN FEATURE SECTION -->
<div class="section">
    <div class="container">
        <?php echo $this->partial('partial/page/offer'); ?>
    </div><!-- /.container -->
</div><!-- /.section -->
<!-- END FEATURE SECTION -->



<!-- BEGIN LATEST WORK SECTION -->
<div class="section work-section">
    <div class="container">
        <?php echo $this->partial('partial/page/gallery'); ?>
    </div><!-- /.container -->
</div><!-- /.section -->
<!-- END LATEST WORK SECTION -->



<!-- BEGIN HAPPY CLIENT SECTION -->
<div class="section bg-light">
    <div class="container">
        <?php echo $this->partial('partial/page/testimonials'); ?>
    </div><!-- /.container -->
</div><!-- /.section -->
<!-- END HAPPY CLIENT SECTION -->



<!-- BEGIN CLIENT LOGO SECTION -->
<div class="section">
    <div class="container">
        <?php echo $this->partial('partial/page/banners'); ?>
    </div><!-- /.container -->
</div><!-- /.section -->
<!-- END CLIENT LOGO SECTION -->