<?php $dictionaryFilename = $dictionary->getFilename() ?>
<?php if(!empty($dictionaryFilename)): ?>
    <section class="main-content" style="background-image: url(<?php echo $this->basePath() ?>/files/dictionary/<?php echo $dictionaryFilename ?>);">
<?php else: ?>
    <section class="main-content" style="background-image: url(/img/bg-kolekcje.png);">
<?php endif ?>

    <div class="header">
        <div class="col-sm-6"></div>
        <div class="col-sm-6 red-line"></div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2><?php echo $dictionary->getname() ?></h2>
            </div>
        </div>

        <?php if($dictionary->getCategory() == 'kolekcje'): ?>

            <?php $col = array_chunk($collections, 3) ?>

            <?php foreach($col as $c): ?>

                <div class="row kolekcje-wiersz">

                    <?php /* @var $post \CmsIr\Post\Model\Post */ ?>
                    <?php foreach($c as $post): ?>
                        <?php $filename = $post->getFilenameMain() ?>

                        <?php if(!empty($filename)): ?>

                            <div class="col-sm-4">
                                <a href="<?php echo $this->url('oneCollection', array('slug' => $post->getCategory(), 'url' => $post->getUrl())) ?>" class="inner-border">
                                    <img src="<?php echo $this->basePath() ?>/files/post/<?php echo $post->getFilenameMain() ?>" alt="" class="img-responsive" />
                                    <p><span><?php echo $post->getName() ?></span></p>
                                </a>
                            </div>

                        <?php endif ?>

                    <?php endforeach ?>

                </div>

            <?php endforeach ?>

        <?php else: ?>

            <?php $col = array_chunk($collections, 2) ?>

            <?php foreach($col as $c): ?>

                <div class="row kolekcje-wiersz">

                    <?php /* @var $post \CmsIr\Post\Model\Post */ ?>
                    <?php foreach($c as $post): ?>
                        <?php $filename = $post->getFilenameMain() ?>

                        <?php if(!empty($filename)): ?>

                            <div class="col-sm-6">
                                <a href="<?php echo $this->url('oneCollection', array('slug' => $post->getCategory(), 'url' => $post->getUrl())) ?>" class="inner-border">
                                    <img src="<?php echo $this->basePath() ?>/files/post/<?php echo $post->getFilenameMain() ?>" alt="" class="img-responsive" />
                                    <p><span><?php echo $post->getName() ?></span></p>
                                </a>
                            </div>

                        <?php endif ?>

                    <?php endforeach ?>

                </div>

            <?php endforeach ?>

        <?php endif ?>

    </div>
</section>