<section class="main-content" style="background-image: url(/img/bg-kolekcje.png);">
    <div class="header">
        <div class="col-sm-6"></div>
        <div class="col-sm-6 red-line"></div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <?php /* @var $page \CmsIr\Page\Model\Page */ ?>
                <h2><?php echo $page->getName() ?></h2>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="description-bottom">
                    <?php echo $page->getContent() ?>
                </div>
            </div>
        </div>

    </div>
</section>