<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Szyk')) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->appendStylesheet($this->basePath() . '/css/flickity.css')
                        ->appendStylesheet($this->basePath() . '/css/front-style.css')
                        ->appendStylesheet($this->basePath() . '/css/media_queries.css')
                        ->appendStylesheet($this->basePath() . '/css/jquery.fancybox.css')
        ?>

        <?php echo $this->headScript()
            ->appendFile($this->basePath() . '/js/jquery.min.js')
            ->appendFile($this->basePath() . '/js/flickity.pkgd.min.js')
            ->appendFile($this->basePath() . '/js/jquery.fancybox.js')
        ?>

        <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700&subset=latin,cyrillic-ext,greek-ext,greek,vietnamese,latin-ext,cyrillic' rel='stylesheet' type='text/css'>

    </head>
    <body class="tooltips">
    <?php echo $this->partial('partial/layout/header'); ?>
    <?php echo $content; ?>
    <?php echo $this->partial('partial/layout/footer'); ?>

    </body>
</html>
