<?php $this->layout('layout/error') ?>

<div class="login-header text-center">
    <img src="<?php echo $this->basePath() ?>/img/logo-login.png" class="logo" alt="Logo">
</div>
<div class="login-wrapper">
    <h1 class="error-number">4<i class="fa fa-meh-o icon-xl icon-square"></i>4</h1>
    <p class="text-center"><strong><a href="<?php echo $this->url('home') ?>">Wróć do strony głównej</a></strong></p>
</div>