<div id="owl-client-logo" class="owl-carousel client-logo">
    <div class="item">
        <img src="<?php echo $this->basePath(); ?>/img/client-logo/graphicriver.png" alt="Client logo">
    </div><!-- /.item -->
    <div class="item">
        <img src="<?php echo $this->basePath(); ?>/img/client-logo/photodune.png" alt="Client logo">
    </div><!-- /.item -->
    <div class="item">
        <img src="<?php echo $this->basePath(); ?>/img/client-logo/themeforest.png" alt="Client logo">
    </div><!-- /.item -->
    <div class="item">
        <img src="<?php echo $this->basePath(); ?>/img/client-logo/codecanyon.png" alt="Client logo">
    </div><!-- /.item -->
    <div class="item">
        <img src="<?php echo $this->basePath(); ?>/img/client-logo/3docean.png" alt="Client logo">
    </div><!-- /.item -->
    <div class="item">
        <img src="<?php echo $this->basePath(); ?>/img/client-logo/graphicriver.png" alt="Client logo">
    </div><!-- /.item -->
    <div class="item">
        <img src="<?php echo $this->basePath(); ?>/img/client-logo/photodune.png" alt="Client logo">
    </div><!-- /.item -->
    <div class="item">
        <img src="<?php echo $this->basePath(); ?>/img/client-logo/themeforest.png" alt="Client logo">
    </div><!-- /.item -->
    <div class="item">
        <img src="<?php echo $this->basePath(); ?>/img/client-logo/codecanyon.png" alt="Client logo">
    </div><!-- /.item -->
    <div class="item">
        <img src="<?php echo $this->basePath(); ?>/img/client-logo/3docean.png" alt="Client logo">
    </div><!-- /.item -->
</div><!-- /#owl-client-logo -->