<div class="section-heading">
    <div class="inner-border"></div>
    <h3>LATEST WORK</h3>
</div><!-- /.section-heading -->
<ul class="work-category-wrap">
    <li class="filter" data-filter="all">ALL</li>
    <li class="filter" data-filter="template">TEMPLATE</li>
    <li class="filter" data-filter="web_design">WEB DESIGN</li>
    <li class="filter" data-filter="mobile_apps">MOBILE APPS</li>
    <li class="filter" data-filter="printing">PRINTING</li>
    <li class="filter" data-filter="other">OTHER</li>
</ul>

<div id="work-mixitup" class="work-content">
    <div class="row">

        <!-- Begin work item -->
        <div class="col-sm-4 col-md-3 col-xs-6 mix printing">
            <div class="work-item">
                <div class="hover-wrap">
                    <a href="#">
                        <i class="glyphicon glyphicon-plus icon-plus"></i>
                    </a>
                </div><!-- /.hover-wrap -->
                <img src="<?php echo $this->basePath(); ?>/img/work/work.jpg" alt="Img work">
                <div class="the-box no-border transparent no-margin">
                    <p class="project-name">Awesome project name</p>
                    <p class="project-category">PRINTING</p>
                </div><!-- /.the-box no-border transparent -->
            </div><!-- /.work-item -->
        </div><!-- /.col-sm-4 col-md-3 col-xs-6 mix -->
        <!-- End work item -->

        <!-- Begin work item -->
        <div class="col-sm-4 col-md-3 col-xs-6 mix template">
            <div class="work-item">
                <div class="hover-wrap">
                    <a href="#">
                        <i class="glyphicon glyphicon-plus icon-plus"></i>
                    </a>
                </div><!-- /.hover-wrap -->
                <img src="<?php echo $this->basePath(); ?>/img/work/work.jpg" alt="Img work">
                <div class="the-box no-border transparent no-margin">
                    <p class="project-name">Awesome project name</p>
                    <p class="project-category">TEMPLATE</p>
                </div><!-- /.the-box no-border transparent -->
            </div><!-- /.work-item -->
        </div><!-- /.col-sm-4 col-md-3 col-xs-6 mix -->
        <!-- End work item -->

        <!-- Begin work item -->
        <div class="col-sm-4 col-md-3 col-xs-6 mix web_design">
            <div class="work-item">
                <div class="hover-wrap">
                    <a href="#">
                        <i class="glyphicon glyphicon-plus icon-plus"></i>
                    </a>
                </div><!-- /.hover-wrap -->
                <img src="<?php echo $this->basePath(); ?>/img/work/work.jpg" alt="Img work">
                <div class="the-box no-border transparent no-margin">
                    <p class="project-name">Awesome project name</p>
                    <p class="project-category">WEB DESIGN</p>
                </div><!-- /.the-box no-border transparent -->
            </div><!-- /.work-item -->
        </div><!-- /.col-sm-4 col-md-3 col-xs-6 mix -->
        <!-- End work item -->

        <!-- Begin work item -->
        <div class="col-sm-4 col-md-3 col-xs-6 mix mobile_apps">
            <div class="work-item">
                <div class="hover-wrap">
                    <a href="#">
                        <i class="glyphicon glyphicon-plus icon-plus"></i>
                    </a>
                </div><!-- /.hover-wrap -->
                <img src="<?php echo $this->basePath(); ?>/img/work/work.jpg" alt="Img work">
                <div class="the-box no-border transparent no-margin">
                    <p class="project-name">Awesome project name</p>
                    <p class="project-category">MOBILE APPS</p>
                </div><!-- /.the-box no-border transparent -->
            </div><!-- /.work-item -->
        </div><!-- /.col-sm-4 col-md-3 col-xs-6 mix -->
        <!-- End work item -->

        <!-- Begin work item -->
        <div class="col-sm-4 col-md-3 col-xs-6 mix template">
            <div class="work-item">
                <div class="hover-wrap">
                    <a href="#">
                        <i class="glyphicon glyphicon-plus icon-plus"></i>
                    </a>
                </div><!-- /.hover-wrap -->
                <img src="<?php echo $this->basePath(); ?>/img/work/work.jpg" alt="Img work">
                <div class="the-box no-border transparent no-margin">
                    <p class="project-name">Awesome project name</p>
                    <p class="project-category">TEMPLATE</p>
                </div><!-- /.the-box no-border transparent -->
            </div><!-- /.work-item -->
        </div><!-- /.col-sm-4 col-md-3 col-xs-6 mix -->
        <!-- End work item -->

        <!-- Begin work item -->
        <div class="col-sm-4 col-md-3 col-xs-6 mix mobile_apps">
            <div class="work-item">
                <div class="hover-wrap">
                    <a href="#">
                        <i class="glyphicon glyphicon-plus icon-plus"></i>
                    </a>
                </div><!-- /.hover-wrap -->
                <img src="<?php echo $this->basePath(); ?>/img/work/work.jpg" alt="Img work">
                <div class="the-box no-border transparent no-margin">
                    <p class="project-name">Awesome project name</p>
                    <p class="project-category">MOBILE APPS</p>
                </div><!-- /.the-box no-border transparent -->
            </div><!-- /.work-item -->
        </div><!-- /.col-sm-4 col-md-3 col-xs-6 mix -->
        <!-- End work item -->

        <!-- Begin work item -->
        <div class="col-sm-4 col-md-3 col-xs-6 mix printing">
            <div class="work-item">
                <div class="hover-wrap">
                    <a href="#">
                        <i class="glyphicon glyphicon-plus icon-plus"></i>
                    </a>
                </div><!-- /.hover-wrap -->
                <img src="<?php echo $this->basePath(); ?>/img/work/work.jpg" alt="Img work">
                <div class="the-box no-border transparent no-margin">
                    <p class="project-name">Awesome project name</p>
                    <p class="project-category">PRINTING</p>
                </div><!-- /.the-box no-border transparent -->
            </div><!-- /.work-item -->
        </div><!-- /.col-sm-4 col-md-3 col-xs-6 mix -->
        <!-- End work item -->

        <!-- Begin work item -->
        <div class="col-sm-4 col-md-3 col-xs-6 mix other">
            <div class="work-item">
                <div class="hover-wrap">
                    <a href="#">
                        <i class="glyphicon glyphicon-plus icon-plus"></i>
                    </a>
                </div><!-- /.hover-wrap -->
                <img src="<?php echo $this->basePath(); ?>/img/work/work.jpg" alt="Img work">
                <div class="the-box no-border transparent no-margin">
                    <p class="project-name">Awesome project name</p>
                    <p class="project-category">OTHER</p>
                </div><!-- /.the-box no-border transparent -->
            </div><!-- /.work-item -->
        </div><!-- /.col-sm-4 col-md-3 col-xs-6 mix -->
        <!-- End work item -->

    </div><!-- /.row -->
</div><!-- /#work-mixitup -->