<div class="row">
    <div class="col-sm-3">
        <div class="the-box bg-danger no-border box-feature text-center">
            <h4 class="heading">RESPONSIVE</h4>
            <i class="fa fa-css3 icon-lg"></i>
            <div class="p-wrap">
                <p>
                    Duis autem vel eum iriure dolor in
                    hendrerit in vulputate velit esse
                    molestie consequat
                </p>
            </div><!-- /.p-wrap -->
            <div class="btn-wrap">
                <button class="btn btn-danger btn-learn-more">LEARN MORE</button>
            </div><!-- /.btn-wrap -->
        </div><!-- /.the-box bg-danger no-border box-feature text-center -->
    </div><!-- /.col-sm-3 -->
    <div class="col-sm-3">
        <div class="the-box bg-warning no-border box-feature text-center">
            <h4 class="heading">RETINA READY</h4>
            <i class="fa fa-female icon-lg"></i>
            <p>
                Duis autem vel eum iriure dolor in
                hendrerit in vulputate velit esse
                molestie consequat
            </p>
            <div class="btn-wrap">
                <button class="btn btn-warning btn-learn-more">LEARN MORE</button>
            </div><!-- /.btn-wrap -->
        </div><!-- /.the-box bg-warning no-border box-feature text-center -->
    </div><!-- /.col-sm-3 -->
    <div class="col-sm-3">
        <div class="the-box bg-success no-border box-feature text-center">
            <h4 class="heading">FLAT DESIGN</h4>
            <i class="fa fa-circle-o-notch icon-lg"></i>
            <p>
                Duis autem vel eum iriure dolor in
                hendrerit in vulputate velit esse
                molestie consequat
            </p>
            <div class="btn-wrap">
                <button class="btn btn-success btn-learn-more">LEARN MORE</button>
            </div><!-- /.btn-wrap -->
        </div><!-- /.the-box bg-success no-border box-feature text-center -->
    </div><!-- /.col-sm-3 -->
    <div class="col-sm-3">
        <div class="the-box bg-info no-border box-feature text-center">
            <h4 class="heading">CLEAN CODE</h4>
            <i class="fa fa-code icon-lg"></i>
            <p>
                Duis autem vel eum iriure dolor in
                hendrerit in vulputate velit esse
                molestie consequat
            </p>
            <div class="btn-wrap">
                <button class="btn btn-info btn-learn-more">LEARN MORE</button>
            </div><!-- /.btn-wrap -->
        </div><!-- /.the-box bg-info no-border box-feature text-center -->
    </div><!-- /.col-sm-3 -->
</div><!-- /.row -->