<div class="slide-text-content">
    <div class="container-fluid">
        <div id="content-header-slide" class="owl-carousel">
            <?php if(!empty($items)): ?>

                <?php /* @var $item \CmsIr\Slider\Model\SliderItem */?>
                <?php foreach($items as $item): ?>
                    <?php $title = $item->getTitle() ?>
                    <?php $description = $item->getDescription()?>

                    <div class="item">
                        <img src="<?php echo $this->basePath('files/slider/' . $item->getFilename()); ?>" class="img-responsive" alt="image"/>
                        <?php if(!empty($title)): ?>
                            <h1><?php echo  $title ?></h1>
                        <?php endif ?>
                        <div class="clear"></div>
                        <?php if(!empty($description)): ?>
                            <h3><?php echo $description?></h3>
                        <?php endif ?>
                    </div>
                    
                <?php endforeach ?>

            <?php endif ?>
        </div><!-- /.#content-header-slide -->
    </div><!-- /.container -->
</div><!-- /.slide-text-content -->