<div class="section-heading">
    <div class="inner-border"></div>
    <h3>HAPPY CLIENT</h3>
</div><!-- /.section-heading -->

<div id="owl-testimonial" class="owl-carousel testimonial">
    <div class="item">
        <p class="text-testi">
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
            Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.Duis autem vel eum iriure
            dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et
            iusto odio dignissim qui blandit praesent
        </p>
        <img src="<?php echo $this->basePath(); ?>/img/avatar/small/avatar.jpg" class="avatar img-circle" alt="Avatar">
        <p class="client-name">Karen Wallace</p>
        <p class="client-home text-danger">CEO - Yogyakarta, Indonesia</p>
    </div><!-- /.item -->
    <div class="item">
        <p class="text-testi">
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
            Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.Duis autem vel eum iriure
            dolor in hendrerit in vulputate velit esse molestie consequat
        </p>
        <img src="<?php echo $this->basePath(); ?>/img/avatar/small/avatar.jpg" class="avatar img-circle" alt="Avatar">
        <p class="client-name">Phillip Lucas</p>
        <p class="client-home text-danger">CEO - Yogyakarta, Indonesia</p>
    </div><!-- /.item -->
    <div class="item">
        <p class="text-testi">
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
            Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.Duis autem vel eum iriure
        </p>
        <img src="<?php echo $this->basePath(); ?>/img/avatar/small/avatar.jpg" class="avatar img-circle" alt="Avatar">
        <p class="client-name">Sandra Myers</p>
        <p class="client-home text-danger">CEO - Yogyakarta, Indonesia</p>
    </div><!-- /.item -->
</div><!-- /#owl-testimonial -->