<!-- Modal -->
<div class="modal fade" id="newsletterModal" tabindex="-1" role="dialog" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Newsletter</h4>
            </div>
            <form action="" method="post">

                <div class="modal-body">
                    <input type="hidden" name="id" value="" />
                    <p>
                        Na podany adres email został wysłany link potwierdzający subskrypcję.
                    </p>
                </div>
                <div class="modal-footer">
                    <input type="submit" name="del" value="Zamknij" class="btn btn-default" data-dismiss="modal"/>
                </div><!-- /.modal-footer -->

            </form>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-doalog -->
</div><!-- /#deleteModal -->