<div class="col-sm-6 col-md-3">
    <h4>CONTACT</h4>
    <div class="media media-contact">
          <span class="pull-left">
                <i class="fa fa-map-marker media-object"></i>
          </span>
        <div class="media-body">
            <address>
                Twitter, Inc.<br>
                795 Folsom Ave, Suite 600<br>
                San Francisco, CA 94107<br>
                <abbr title="Phone">P:</abbr> (123) 456-7890
            </address>
        </div><!-- /.media-body -->
    </div><!-- /.media -->
    <div class="media media-contact">
						  <span class="pull-left">
							<i class="fa fa-envelope media-object"></i>
						  </span>
        <div class="media-body">
            <address>
                Full Name<br>
                <a href="mailto:#">first.last@example.com</a>
            </address>
        </div><!-- /.media-body -->
    </div><!-- /.media -->
</div><!-- /.col-sm-3 -->