<footer>
    <div class="container">
        <div class="row">
            <div class="col-sm-5">

                <?php echo $this->menuHelper()->renderSecondMenu($menu, 'menuH decor1', null, null, null); ?>


            </div>
            <div class="col-sm-7">
                <p>Szyk Śląsk © 2015</p>
                <p>Wszelkie prawa zastrzeżone</p>
                <p><span>projekt i wykonanie:</span><a href="http://www.fabrykakreacji.com"><img src="/img/fabryka.png" alt="fabryka"/></a></p>
            </div>
        </div>
    </div>

</footer>