<!-- BEGIN FOOTER -->
<footer class="light-color">
    <div class="container">
        <div class="row">
            <?php echo $this->partial('partial/layout/footer-about'); ?>
            <?php echo $this->partial('partial/layout/footer-contact'); ?>



            <div class="clearfix visible-sm"></div>
            <?php echo $this->partial('partial/layout/footer-navigation'); ?>
            <?php echo $this->partial('partial/layout/footer-newsletter'); ?>
        </div><!-- /.row -->
    </div><!-- /.container -->
</footer><!-- /.section -->

<?php echo $this->partial('partial/layout/footer-terms'); ?>

<!-- END FOOTER -->