<!-- Begin logo -->
<div class="logo">
    <a href="index.html"><img src="<?php echo $this->basePath(); ?>/img/logo-black.png" alt="Logo"></a>
</div><!-- /.logo -->
<!-- End logo -->

<!-- Begin button toggle nav -->
<div class="btn-toggle-nav" id="btn-toggle-nav"><i class="fa fa-bars"></i></div>
<div class="btn-toggle-search" id="btn-icon-search"><i class="fa fa-search"></i></div>
<div class="btn-toggle-phone" id="btn-icon-phone"><i class="fa fa-phone"></i></div>
<!-- End button toggle nav -->

<!-- Begin visible phone and search nav -->
<div id="phone-sub" class="nav-right-info">
    <i class="fa fa-times times-icon" id="close-phone-nav"></i>
    <p class="phone">Call us : <strong>+1 123 4567 7899</strong></p>
</div>
<div id="search-sub" class="nav-right-info">
    <i class="fa fa-times times-icon" id="close-search-nav"></i>
    <form role="form">
        <input type="text" class="form-control" placeholder="Search something...">
    </form>
</div>
<!-- End visible phone and search nav -->